import type { Booking } from '@/types';

export const mockBookings: Booking[] = [
  {
    id: 'b1',
    clientName: 'Sarah Mitchell',
    clientId: 'c1',
    sessionType: 'Wedding',
    date: '2026-03-22',
    time: '10:00',
    location: 'Loose Park, Kansas City',
    status: 'confirmed',
    totalAmount: 2400,
    depositAmount: 800,
    depositPaid: true,
    contractSigned: true,
    shootId: 's1',
    notes: 'Ceremony at 11am. Reception at The Grandview.',
  },
  {
    id: 'b2',
    clientName: 'James & Priya Okafor',
    clientId: 'c2',
    sessionType: 'Engagement',
    date: '2026-03-25',
    time: '16:30',
    location: 'River Market, KC',
    status: 'confirmed',
    totalAmount: 850,
    depositAmount: 200,
    depositPaid: true,
    contractSigned: true,
    shootId: 's2',
  },
  {
    id: 'b3',
    clientName: 'The Henderson Family',
    clientId: 'c3',
    sessionType: 'Family',
    date: '2026-03-28',
    time: '09:00',
    location: 'Shawnee Mission Park',
    status: 'pending',
    totalAmount: 550,
    depositAmount: 150,
    depositPaid: false,
    contractSigned: false,
    notes: 'Awaiting deposit and signed contract.',
  },
  {
    id: 'b4',
    clientName: 'Megan Torres',
    clientId: 'c4',
    sessionType: 'Newborn',
    date: '2026-04-02',
    time: '11:00',
    location: 'Studio',
    status: 'confirmed',
    totalAmount: 695,
    depositAmount: 200,
    depositPaid: true,
    contractSigned: true,
    shootId: 's4',
  },
  {
    id: 'b5',
    clientName: 'Derek Paulson',
    clientId: 'c5',
    sessionType: 'Headshots',
    date: '2026-04-05',
    time: '14:00',
    location: 'Studio',
    status: 'confirmed',
    totalAmount: 320,
    depositAmount: 100,
    depositPaid: true,
    contractSigned: true,
  },
  {
    id: 'b6',
    clientName: 'Olivia & Ben Hartley',
    clientId: 'c6',
    sessionType: 'Wedding',
    date: '2026-06-14',
    time: '11:00',
    location: 'The Elms Hotel, Excelsior Springs',
    status: 'pending',
    totalAmount: 2800,
    depositAmount: 900,
    depositPaid: false,
    contractSigned: false,
    notes: 'Lead from Sarah Mitchell referral. First consultation scheduled.',
  },
  {
    id: 'b7',
    clientName: 'Yuki Tanaka',
    clientId: 'c9',
    sessionType: 'Portrait',
    date: '2026-04-18',
    time: '15:00',
    location: 'Studio',
    status: 'confirmed',
    totalAmount: 420,
    depositAmount: 120,
    depositPaid: true,
    contractSigned: true,
  },
  {
    id: 'b8',
    clientName: 'Derek Paulson',
    clientId: 'c5',
    sessionType: 'Headshots',
    date: '2026-01-15',
    time: '14:00',
    location: 'Studio',
    status: 'completed',
    totalAmount: 320,
    depositAmount: 100,
    depositPaid: true,
    contractSigned: true,
    shootId: 's5',
  },
  {
    id: 'b9',
    clientName: 'Nina Vasquez',
    clientId: 'c7',
    sessionType: 'Portrait',
    date: '2025-11-20',
    time: '10:00',
    location: 'Loose Park',
    status: 'completed',
    totalAmount: 450,
    depositAmount: 150,
    depositPaid: true,
    contractSigned: true,
  },
  {
    id: 'b10',
    clientName: 'The Henderson Family',
    clientId: 'c3',
    sessionType: 'Family',
    date: '2026-05-10',
    time: '09:30',
    location: 'Shawnee Mission Park',
    status: 'cancelled',
    totalAmount: 550,
    depositAmount: 150,
    depositPaid: false,
    contractSigned: false,
    notes: 'Client cancelled — rescheduling for fall.',
  },
];
