import type { PricingPackage } from '@/types';

export const DISCOUNT_CODES: Record<string, number> = {
  WELCOME10: 10,
  REFER20: 20,
  SEASONAL15: 15,
  VIP25: 25,
};

export const mockPackages: PricingPackage[] = [
  {
    id: 'pkg1',
    name: 'Essential Wedding',
    category: 'Wedding',
    description: 'Perfect for intimate ceremonies and elopements.',
    basePrice: 1800,
    popular: false,
    includes: [
      '6 hours of coverage',
      '1 photographer',
      'Online gallery (300+ edited images)',
      'Print release',
    ],
    addOns: [
      {
        id: 'a1',
        label: 'Extra hour',
        price: 250,
        description: 'Additional coverage hour',
      },
      {
        id: 'a2',
        label: 'Second shooter',
        price: 400,
        description: 'Full day second photographer',
      },
      {
        id: 'a3',
        label: 'Engagement session',
        price: 350,
        description: '1.5hr engagement shoot',
      },
      {
        id: 'a4',
        label: 'Premium album (10x10)',
        price: 600,
        description: '30-page heirloom album',
      },
      {
        id: 'a5',
        label: 'Rush delivery (2 weeks)',
        price: 300,
        description: 'Expedited editing',
      },
    ],
  },
  {
    id: 'pkg2',
    name: 'Classic Wedding',
    category: 'Wedding',
    description: 'Our most popular wedding package for full-day coverage.',
    basePrice: 2800,
    popular: true,
    includes: [
      '10 hours of coverage',
      '1 photographer',
      'Engagement session included',
      'Online gallery (500+ edited images)',
      'Print release',
      '8x8 highlight album',
    ],
    addOns: [
      { id: 'a1', label: 'Extra hour', price: 250 },
      { id: 'a2', label: 'Second shooter', price: 400 },
      { id: 'a4', label: 'Upgrade to 10x10 album', price: 300 },
      { id: 'a5', label: 'Rush delivery (2 weeks)', price: 300 },
      {
        id: 'a6',
        label: 'Rehearsal dinner coverage',
        price: 500,
        description: '2 hours',
      },
    ],
  },
  {
    id: 'pkg3',
    name: 'Luxury Wedding',
    category: 'Wedding',
    description: 'All-inclusive coverage for your perfect day.',
    basePrice: 4200,
    popular: false,
    includes: [
      'Full day coverage (up to 12 hours)',
      'Lead photographer + second shooter',
      'Engagement session included',
      'Rehearsal dinner (2 hours)',
      'Online gallery (700+ edited images)',
      'Print release',
      'Premium 12x12 album (40 pages)',
      'Two 8x10 parent albums',
    ],
    addOns: [
      { id: 'a1', label: 'Extra hour', price: 250 },
      { id: 'a5', label: 'Rush delivery (2 weeks)', price: 300 },
      { id: 'a7', label: 'Bridal boudoir session', price: 450 },
      {
        id: 'a8',
        label: 'Fine art prints set',
        price: 350,
        description: 'Set of 5 framed prints',
      },
    ],
  },
  {
    id: 'pkg4',
    name: 'Portrait Session',
    category: 'Portrait',
    description: 'Individual or couple portraits for any occasion.',
    basePrice: 350,
    popular: false,
    includes: [
      '1 hour session',
      '1 location',
      'Online gallery (50+ edited images)',
      'Print release',
    ],
    addOns: [
      { id: 'a1', label: 'Extra 30 minutes', price: 100 },
      { id: 'a9', label: 'Second location', price: 75 },
      { id: 'a10', label: 'Outfit change', price: 50 },
      { id: 'a11', label: 'Print package (5 prints)', price: 120 },
    ],
  },
  {
    id: 'pkg5',
    name: 'Family Session',
    category: 'Family',
    description: 'Relaxed family portraits at your favourite location.',
    basePrice: 495,
    popular: true,
    includes: [
      '90 minute session',
      'Up to 6 family members',
      '1 location',
      'Online gallery (75+ edited images)',
      'Print release',
    ],
    addOns: [
      { id: 'a1', label: 'Extra 30 minutes', price: 100 },
      { id: 'a9', label: 'Second location', price: 75 },
      { id: 'a11', label: 'Print package (5 prints)', price: 120 },
      { id: 'a12', label: 'Canvas wrap (16x20)', price: 180 },
    ],
  },
  {
    id: 'pkg6',
    name: 'Newborn Session',
    category: 'Newborn',
    description: 'Timeless newborn portraits in the first two weeks of life.',
    basePrice: 595,
    popular: false,
    includes: [
      'Up to 3 hours studio session',
      'Baby, sibling & family setups',
      'Online gallery (60+ edited images)',
      'Print release',
    ],
    addOns: [
      { id: 'a11', label: 'Print package (5 prints)', price: 120 },
      { id: 'a12', label: 'Canvas wrap (16x20)', price: 180 },
      { id: 'a13', label: 'Maternity session add-on', price: 250 },
    ],
  },
  {
    id: 'pkg7',
    name: 'Headshots',
    category: 'Headshots',
    description:
      'Professional headshots for LinkedIn, press, or corporate use.',
    basePrice: 295,
    popular: false,
    includes: [
      '45 minute studio session',
      '2 background options',
      'Online gallery (30+ edited images)',
      'Print release',
      'LinkedIn-optimised crop',
    ],
    addOns: [
      { id: 'a1', label: 'Extra 30 minutes', price: 100 },
      {
        id: 'a14',
        label: 'Additional team member',
        price: 150,
        description: 'Per person',
      },
      { id: 'a15', label: 'Lifestyle/office shots', price: 200 },
    ],
  },
];
