import type { Booking, Client } from '@/types';

export const mockStats = {
  revenueMonth: 4850,
  revenueLastMonth: 3920,
  upcomingBookings: 6,
  upcomingBookingsLastMonth: 4,
  activeClients: 23,
  activeClientsLastMonth: 19,
  pendingInvoices: 3,
  pendingInvoicesAmount: 1240,
};

export const mockUpcomingBookings: Booking[] = [
  {
    id: 'b1',
    clientId: 'c1',
    clientName: 'Sarah Mitchell',
    sessionType: 'Wedding',
    date: '2026-03-22T10:00:00',
    location: 'Loose Park, Kansas City',
    status: 'confirmed',
    depositPaid: true,
    totalAmount: 2400,
  },
  {
    id: 'b2',
    clientId: 'c2',
    clientName: 'James & Priya Okafor',
    sessionType: 'Engagement',
    date: '2026-03-25T16:30:00',
    location: 'River Market, KC',
    status: 'confirmed',
    depositPaid: true,
    totalAmount: 850,
  },
  {
    id: 'b3',
    clientId: 'c3',
    clientName: 'The Henderson Family',
    sessionType: 'Family Portrait',
    date: '2026-03-28T09:00:00',
    location: 'Shawnee Mission Park',
    status: 'pending',
    depositPaid: false,
    totalAmount: 550,
  },
  {
    id: 'b4',
    clientId: 'c4',
    clientName: 'Megan Torres',
    sessionType: 'Newborn',
    date: '2026-04-02T11:00:00',
    location: 'Studio',
    status: 'confirmed',
    depositPaid: true,
    totalAmount: 695,
  },
  {
    id: 'b5',
    clientId: 'c5',
    clientName: 'Derek Paulson',
    sessionType: 'Headshots',
    date: '2026-04-05T14:00:00',
    location: 'Studio',
    status: 'confirmed',
    depositPaid: true,
    totalAmount: 320,
  },
];

export const mockRecentClients: Client[] = [
  {
    id: 'c1',
    name: 'Sarah Mitchell',
    email: 'sarah.mitchell@email.com',
    phone: '816-555-0192',
    status: 'active',
    createdAt: '2026-01-14',
    totalShoots: 1,
    totalRevenue: 2400,
  },
  {
    id: 'c2',
    name: 'James & Priya Okafor',
    email: 'okafor.family@email.com',
    phone: '913-555-0847',
    status: 'active',
    createdAt: '2026-02-03',
    totalShoots: 1,
    totalRevenue: 850,
  },
  {
    id: 'c3',
    name: 'The Henderson Family',
    email: 'chenderson@email.com',
    phone: '816-555-0334',
    status: 'lead',
    createdAt: '2026-03-10',
    totalShoots: 0,
    totalRevenue: 0,
  },
  {
    id: 'c4',
    name: 'Megan Torres',
    email: 'm.torres@email.com',
    phone: '816-555-0571',
    status: 'active',
    createdAt: '2026-02-18',
    totalShoots: 2,
    totalRevenue: 1390,
  },
  {
    id: 'c5',
    name: 'Derek Paulson',
    email: 'dpaulson@email.com',
    status: 'active',
    createdAt: '2026-03-01',
    totalShoots: 1,
    totalRevenue: 320,
  },
];

export const mockRevenueChart = [
  { month: 'Oct', revenue: 2100 },
  { month: 'Nov', revenue: 3400 },
  { month: 'Dec', revenue: 5200 },
  { month: 'Jan', revenue: 2800 },
  { month: 'Feb', revenue: 3920 },
  { month: 'Mar', revenue: 4850 },
];
