import type { GearItem } from '@/types';

export const mockGear: GearItem[] = [
  // Bodies
  {
    id: 'g1',
    name: 'Sony A7 IV',
    category: 'body',
    serialNumber: 'SN-4421892',
    purchaseDate: '2023-03-15',
    purchasePrice: 2498,
    insuranceValue: 2200,
    condition: 'excellent',
    notes: 'Primary body. Shutter count ~18k.',
  },
  {
    id: 'g2',
    name: 'Sony A7 III',
    category: 'body',
    serialNumber: 'SN-3301445',
    purchaseDate: '2021-07-04',
    purchasePrice: 1999,
    insuranceValue: 1400,
    condition: 'good',
    notes: 'Backup body. Shutter count ~62k.',
  },
  // Lenses
  {
    id: 'g3',
    name: 'Sony 85mm f/1.4 GM',
    category: 'lens',
    serialNumber: 'SN-8812334',
    purchaseDate: '2023-05-20',
    purchasePrice: 1798,
    insuranceValue: 1600,
    condition: 'excellent',
  },
  {
    id: 'g4',
    name: 'Sony 35mm f/1.4 GM',
    category: 'lens',
    serialNumber: 'SN-7723001',
    purchaseDate: '2022-11-10',
    purchasePrice: 1398,
    insuranceValue: 1200,
    condition: 'excellent',
  },
  {
    id: 'g5',
    name: 'Sony 24-70mm f/2.8 GM II',
    category: 'lens',
    serialNumber: 'SN-6612887',
    purchaseDate: '2022-04-01',
    purchasePrice: 2298,
    insuranceValue: 1900,
    condition: 'good',
    notes: 'Slight dust inside front element — not affecting IQ.',
  },
  {
    id: 'g6',
    name: 'Sony 70-200mm f/2.8 GM II',
    category: 'lens',
    serialNumber: 'SN-5509234',
    purchaseDate: '2021-12-18',
    purchasePrice: 2798,
    insuranceValue: 2400,
    condition: 'needs-repair',
    notes: 'AF intermittently hunting — needs service.',
  },
  // Lighting
  {
    id: 'g7',
    name: 'Profoto B10 Plus',
    category: 'lighting',
    serialNumber: 'PF-998812',
    purchaseDate: '2022-08-30',
    purchasePrice: 1695,
    insuranceValue: 1400,
    condition: 'good',
  },
  {
    id: 'g8',
    name: 'Profoto B10 Plus (2nd)',
    category: 'lighting',
    serialNumber: 'PF-998813',
    purchaseDate: '2022-08-30',
    purchasePrice: 1695,
    insuranceValue: 1400,
    condition: 'excellent',
  },
  {
    id: 'g9',
    name: 'Profoto OCF Softbox 2x3',
    category: 'lighting',
    purchaseDate: '2022-09-05',
    purchasePrice: 189,
    insuranceValue: 150,
    condition: 'good',
  },
  // Accessories
  {
    id: 'g10',
    name: 'Peak Design Camera Strap',
    category: 'accessory',
    purchaseDate: '2023-01-10',
    purchasePrice: 79,
    insuranceValue: 60,
    condition: 'excellent',
  },
  {
    id: 'g11',
    name: 'Sony NP-FZ100 Batteries (x4)',
    category: 'accessory',
    purchaseDate: '2023-03-15',
    purchasePrice: 220,
    insuranceValue: 180,
    condition: 'good',
  },
  {
    id: 'g12',
    name: 'Think Tank Airport Roller',
    category: 'bag',
    purchaseDate: '2022-01-20',
    purchasePrice: 399,
    insuranceValue: 320,
    condition: 'fair',
    notes: 'One wheel slightly wobbly but functional.',
  },
];
